version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gocognit
    - wrapcheck
    - varnamelen
    - err113
    - lll
    - cyclop
    - funlen
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
