version = 0.1

[default.deploy.parameters]
stack_name = "github-runner-autoscaler"
region = "us-east-2"
resolve_s3 = true
s3_prefix = "github-runner-autoscaler"
capabilities = "CAPABILITY_IAM"
GitHubPATSecretName = "github-runner-autoscaler-pat"
ExtraRunnerLabels = "example"
ImageId = "ami-0c0c88099397fccb4"
SubnetId = "subnet-1234567890def"
SecurityGroupIds = "sg-1234567890def"
KeyName = "terraform-20250518"
