version: 0.1
vor_stream_sdlc:
  deploy:
    parameters:
      stack_name: github-runner-autoscaler
      region: us-east-2
      resolve_s3: true
      s3_prefix: github-runner-autoscaler
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - GitHubPATSecretName=github-runner-autoscaler-pat
        - ExtraRunnerLabels=vor-stream-sdlc
        - ImageId=ami-0c0c88099397fccb4
        - SubnetId=subnet-0eb6da43c6f0ef528
        - SecurityGroupIds=sg-0f185b577cb2b2802
        - KeyName=terraform-20220125192645402400000001
