version: 0.1
dev:
  deploy:
    parameters:
      stack_name: github-runner-autoscaler
      region: us-east-2
      resolve_s3: true
      s3_prefix: github-runner-autoscaler
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - GitHubPATSecretName=github-runner-autoscaler-pat
        - ExtraRunnerLabels=dev
        - SubnetTag=github-runner=true
        - SecurityGroupTags=github-runner=true
prod:
  deploy:
    parameters:
      stack_name: github-runner-autoscaler
      region: us-east-2
      resolve_s3: true
      s3_prefix: github-runner-autoscaler
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - GitHubPATSecretName=github-runner-autoscaler-pat
        - ExtraRunnerLabels=prod
        - SubnetTag=github-runner=true
        - SecurityGroupTags=github-runner=true