version: 0.1
dev:
  deploy:
    parameters:
      stack_name: github-runner-autoscaler
      region: us-east-2
      resolve_s3: true
      s3_prefix: github-runner-autoscaler
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - GitHubPATSecretName=github-runner-autoscaler-pat
        - ExtraRunnerLabels=dev
        - ImageId=ami-0c0c88099397fccb4
        - SubnetId=subnet-0123456789def
        - SecurityGroupIds=sg-0123456789def
        - KeyName=terraform-2025051802
prod:
  deploy:
    parameters:
      stack_name: github-runner-autoscaler
      region: us-east-2
      resolve_s3: true
      s3_prefix: github-runner-autoscaler
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - GitHubPATSecretName=github-runner-autoscaler-pat
        - ExtraRunnerLabels=prod
        - ImageId=ami-0c0c88099397fccb4
        - SubnetId=subnet-0123456789def
        - SecurityGroupIds=sg-0123456789def
        - KeyName=terraform-2025051801
