version = 0.1

[default.deploy.parameters]
stack_name = "github-runner-autoscaler"
region = "us-east-2"
resolve_s3 = true
s3_prefix = "github-runner-autoscaler"
[default.deploy.parameters.parameter_overrides]
ImageId = "ami-0c0c88099397fccb4"
GitHubPATSecretName = "github-runner-autoscaler-pat"

[dev.deploy.parameters]
[dev.deploy.parameters.parameter_overrides]
ExtraRunnerLabels = "dev"
SubnetId = "subnet-12345678"
SecurityGroupIds = "sg-12345678"
KeyName = "terraform-20220125192645402400000001"

[prod.deploy.parameters]
[prod.deploy.parameters.parameter_overrides]
ExtraRunnerLabels = "dev"
SubnetId = "subnet-98765432"
SecurityGroupIds = "sg-98765432"
KeyName = "terraform-20220125192645402400000002"
