version = 0.1
[default.deploy.parameters]
stack_name = "github-runner-autoscaler"
resolve_s3 = true
s3_prefix = "github-runner-autoscaler"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
