AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  GitHubPATSecretName:
    Type: String
    Description: Name of the Secrets Manager secret containing the GitHub PAT
  ExtraRunnerLabels:
    Type: String
    Default: ""
    Description: Additional comma separated labels for the runner
  ImageId:
    Type: String
    Description: AMI ID for the runner instances
  SubnetId:
    Type: String
    Description: Subnet ID for the runner instances
  SecurityGroupIds:
    Type: String
    Description: Comma separated security group IDs for the runner
  KeyName:
    Type: String
    Description: EC2 key pair name for the runner
  WarmPoolConfig:
    Type: String
    Default: "{}"
    Description: >
      JSON map of instance type to pool size. Empty {} disables warm pool.
      Example: {"c8a.2xlarge":2,"c8a.4xlarge":1}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  # IAM Role for EC2 instances
  RunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/github-runner:*'
        - PolicyName: SSMJITConfigPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:DeleteParameter
                Resource: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/github-runner/jit-config/*'

  RunnerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RunnerInstanceRole
  GitHubActionHookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Architectures:
        - arm64
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
            RequestParameters:
              - method.request.header.X-GitHub-Event:
                  Required: true
                  Caching: false
        WarmPoolMaintenance:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Maintain warm pool of EC2 instances
            Enabled: true
            Input: '{"source": "warmPoolMaintenance"}'
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          GITHUB_PAT_SECRET_NAME: !Ref GitHubPATSecretName
          EXTRA_RUNNER_LABELS: !Ref ExtraRunnerLabels
          IMAGE_ID: !Ref ImageId
          SUBNET_ID: !Ref SubnetId
          SECURITY_GROUP_IDS: !Ref SecurityGroupIds
          KEY_NAME: !Ref KeyName
          INSTANCE_PROFILE_ARN: !GetAtt RunnerInstanceProfile.Arn
          WARM_POOL_CONFIG: !Ref WarmPoolConfig
      Policies:
        - Statement:
            - Sid: RunInstances
              Effect: Allow
              Action:
                - ssm:GetParameters
                - iam:PassRole
                - ec2:CreateTags
                - ec2:RunInstances
              Resource: "*"
            - Sid: WarmPoolManagement
              Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:ModifyInstanceAttribute
              Resource: "*"
            - Sid: GetGitHubPAT
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GitHubPATSecretName}*
            - Sid: SSMJITConfig
              Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:DeleteParameter
              Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/github-runner/jit-config/*
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GitHubActionHookFunctionAPI:
    Description: "API Gateway endpoint URL for Prod environment for GitHubActionHook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GitHubActionHookFunction:
    Description: "GitHub Action Hook Lambda Function ARN."
    Value: !GetAtt GitHubActionHookFunction.Arn
  GitHubActionHookFunctionIamRole:
    Description: "Implicit IAM Role created for GitHubActionHook function"
    Value: !GetAtt GitHubActionHookFunctionRole.Arn
