name: Code Quality Checks

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: golangci-lint .
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout 5m --config=${{ github.workspace }}/.golangci.yaml
